# This and the Dockerfile are only for building the Linux libraries.
services:
  build-tinyfiledialogs:
    build: .
    volumes:
      - ./tinyfiledialogs:/src
    working_dir: /src
    command: ./build.sh
